client_cert: "/home/igor/.wonder/credentials/imusinov.crt"
client_key: "/home/igor/.wonder/credentials/imusinov.key"
ca_cert: "/home/igor/.wonder/credentials/wonderland.crt"
connect_to: 127.0.0.1:50051
db_uri: postgres://user:123456789@localhost:5432/db2?sslmode=disable
